### ISSUE TITLE
BUG: Calamares option to automatically login does not work

### ISSUE THREAD

**Issue by cat-master21** [rhino-linux/os#49]
During the installation, Calamares gives the option to automatically login without the user password but this does not work.

**Comment by oklopfer** [comment]
We should check this is definitely a downstream us issue and not an upstream calamares issue. moving to rollover

**Comment by ajstrongdev** [comment]
@cat-master21 Does this issue persist in 2023.3?

**Comment by cat-master21** [comment]
I can check later @ajstrongdev but it should if the Calamaris configuration has not changed.

**Comment by ajstrongdev** [comment]
@cat-master21 any update? 

And i considered it was an issue with the installer, and if Calamares have released a chance recently then it could potentially have been fixed, however the last stable release of Calamares was in April, so not much should have changed on that front. Moving to rollover for 2023.5.

**Comment by cat-master21** [comment]
@ajstrongdev it is not fixed I am sure of it. This is not a Calamares issue a rather a issue with the default configuration we use which is Lubuntu's which is set the auto login on LightDM and their session. We would need to change that.

**Comment by oklopfer** [comment]
can confirm it is still not working in 2023.4, so we do have to be the ones to fix it
